export const AUTH_USER = 'AUTH_USER';
export const SIGN_OUT_USER = 'SIGN_OUT_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
export const DISPLAY_ARTICLES = 'DISPLAY_ARTICLES';
export const DISPLAY_COMMENTS = 'DISPLAY_COMMENTS';
export const DISPLAY_USER_INFO = 'DISPLAY_USER_INFO';
